### PR TITLE
Refactor list events formatting and fixed bug on list-n and list-e

### LINKED ISSUE #106: Bug regarding printing empty timetable
image
Printing empty timetable throws an error message rather than command unsuccessful message.

### PR DESCRIPTION
**Pull request by brandonywl**
Added trim and isblank check on user message to Close #106. 

Refactored list events first, will work on add event and delete event on another branch

### CODE REVIEW

File: src/main/java/seedu/duke/command/ListEventCommand.java [hunk 1]
```diff
@@ -25,10 +24,12 @@
...
-    private static final String COMMAND_SUCCESSFUL_MESSAGE = "These are the events in the specified time period: "
-            + Formatter.LS;
-    private static final String COMMAND_UNSUCCESSFUL_MESSAGE = "Failed to find any events in the specified time period."
-            + Formatter.LS;
+    private static final String COMMAND_SUCCESSFUL_GENERIC_MESSAGE = "These are the events stored: ";
+    private static final String COMMAND_UNSUCCESSFUL_GENERIC_MESSAGE = "There are no events stored in the timetable!";
+    private static final String COMMAND_SUCCESSFUL_TIME_PERIOD_MESSAGE = "These are the events "
+            + "in the specified time period: ";
+    private static final String COMMAND_UNSUCCESSFUL_TIME_PERIOD_MESSAGE = "Failed to find any events "
+            + "in the specified time period.";
```
Comment (R-Ramana) [inline src/main/java/seedu/duke/command/ListEventCommand.java:32]: Maybe can add the time period parameter?

**Review by R-Ramana — APPROVED** [review]

File: src/main/java/seedu/duke/data/timetable/RecurringEvent.java [hunk 2]
```diff
@@ -107,6 +107,21 @@ public String toString() {
...
+        ArrayList<String> result = super.toStringArray();
+        String endRecurrenceString = "Until: ";
+        if (!endRecurrenceDate.equals(DEFAULT_END_RECURRENCE)) {
+            endRecurrenceString += endRecurrenceDate.toString();
+        } else {
+            endRecurrenceString += "Forever";
+        }
+        endRecurrenceString = " (" + endRecurrenceString + ")";
+        int lastIndex = result.size() - 1;
+        result.set(lastIndex, result.get(lastIndex) + endRecurrenceString);
```
[the remark this answers is not in the document]
Comment (brandonywl) [reply src/main/java/seedu/duke/data/timetable/RecurringEvent.java:121]: Tried this and the line got too long and unreadable.

File: src/main/java/seedu/duke/data/timetable/RecurringEvent.java [hunk 3]
```diff
@@ -107,6 +107,21 @@ public String toString() {
...
+    @Override
+    public ArrayList<String> toStringArray() {
+        ArrayList<String> result = super.toStringArray();
+        String endRecurrenceString = "Until: ";
+        if (!endRecurrenceDate.equals(DEFAULT_END_RECURRENCE)) {
+            endRecurrenceString += endRecurrenceDate.toString();
+        } else {
+            endRecurrenceString += "Forever";
+        }
+        endRecurrenceString = " (" + endRecurrenceString + ")";
```
[the remark this answers is not in the document]
Comment (brandonywl) [reply src/main/java/seedu/duke/data/timetable/RecurringEvent.java:119]: Sorry but what's the significance of doing that as opposed to +=?

File: src/main/java/seedu/duke/command/ListEventCommand.java (hunk 1 above)
Comment (Chongjx) [reply src/main/java/seedu/duke/command/ListEventCommand.java:32]: He did that in the execute return, since this is a private static final, the time period cannot be added here.

File: src/main/java/seedu/duke/data/timetable/Event.java [hunk 4]
```diff
@@ -217,6 +219,96 @@ public String toString() {
...
+        int i = 1;
+        for (Event event : events) {
+            ArrayList<String> eventString = event.toStringArray();
+            eventString.set(0, i++ + ". " + eventString.get(0));
+            results.addAll(eventString);
+            results.add(" ");
+        }
+        results.remove(results.size() - 1);
+        return results;
+    }
```
Comment (Chongjx) [inline src/main/java/seedu/duke/data/timetable/Event.java:255]: This should be formatEvents or formatTimetable. See suggestion for formatEvent(event) in the #108

File: src/main/java/seedu/duke/data/timetable/Event.java [hunk 5]
```diff
@@ -217,6 +219,96 @@ public String toString() {
...
+        for (Month month: months) {
+            results.add(month.name());
+            results.addAll(monthCalendarToString(calendar.get(month)));
+            results.add(" ");
+        }
+        results.remove(results.size() - 1);
+        results.remove(results.size() - 1);
+        return results;
+    }
+
```
Comment (Chongjx) [inline src/main/java/seedu/duke/data/timetable/Event.java:311]: These functions can just sort and compare the events and eventually just return an arrayList of event.

File: src/main/java/seedu/duke/ui/Formatter.java [hunk 6]
```diff
@@ -56,9 +58,45 @@ public static String formatNote(String header, Note note) {
...
+        String formattedString;
+        if (month != 0) {
+            formattedString = generatesHeader(header + String.format(" %d-%d", year, month));
+        } else {
+            formattedString = generatesHeader(header + " " + year);
+        }
+        ArrayList<String> unformattedEvents = Event.yearCalendarToString(timetable);
+        for (String event : unformattedEvents) {
+            formattedString = formattedString.concat(encloseRow(event));
+        }
```
Comment (Chongjx) [inline src/main/java/seedu/duke/ui/Formatter.java:81]: Possible to change the parameter such that it takes in an arrayList of events instead of HashMap<Month, HashMap<Integer, ArrayList<Event>>> timetable?

File: src/main/java/seedu/duke/ui/Formatter.java [hunk 7]
```diff
@@ -56,9 +58,45 @@ public static String formatNote(String header, Note note) {
...
+     * @param header Success message.
+     * @param events Events to be printed
+     * @return Formatted string of indexed events in timetable
+     */
+    public static String formatTimetable(String header, ArrayList<Event> events) {
+        String formattedString = generatesHeader(header);
+        ArrayList<String> eventStrings = Event.calendarToString(events);
+        for (String event : eventStrings) {
+            formattedString = formattedString.concat(encloseRow(event));
+        }
```
Comment (Chongjx) [inline src/main/java/seedu/duke/ui/Formatter.java:98]: In terms of reusability:
for (Event event: events) {
formattedString = formattedString.concat(formatEvent(event));
}

**Review by Chongjx — CHANGES_REQUESTED** [review]
Suggestion to make all getMonthTimetable/getTimetable to return an arrayList of events. Minimize the need to create hashmap<hashmap<arraylisy>>> object.

File: src/main/java/seedu/duke/ui/Formatter.java (hunk 6 above)
Comment (brandonywl) [reply src/main/java/seedu/duke/ui/Formatter.java:81]: While possible, I'd lose the information on the name of the month and at each event, I'll have to check the month and see if it's different at each step. I'll basically be shifting the processing of each event from Event to here. Is there any significant reason why? If not I feel there's no added benefit to doing so.

File: src/main/java/seedu/duke/data/timetable/RecurringEvent.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (Chongjx) [reply src/main/java/seedu/duke/data/timetable/RecurringEvent.java:119]: There is not much difference, I use concat mainly because intellij will give warning for using += in loop, so I use concat for all cases.

File: src/main/java/seedu/duke/ui/Formatter.java (hunk 6 above)
Comment (Chongjx) [reply src/main/java/seedu/duke/ui/Formatter.java:81]: If thats the case, I think can leave it. The only concern is that the data struct looks complicated haha.

**Review by Chongjx — APPROVED** [review]

File: src/main/java/seedu/duke/data/timetable/RecurringEvent.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (R-Ramana) [reply src/main/java/seedu/duke/data/timetable/RecurringEvent.java:119]: Not much as Jun Xiang mentioned, but I think it would be better if we can standardize the code 👍

File: src/main/java/seedu/duke/ui/Formatter.java (hunk 6 above)
Comment (brandonywl) [reply src/main/java/seedu/duke/ui/Formatter.java:81]: I'll see what I can do as I am already currently pushing in the year and month already. May be able to cut down the data struct shape

File: src/main/java/seedu/duke/ui/Formatter.java (hunk 7 above)
Comment (brandonywl) [reply src/main/java/seedu/duke/ui/Formatter.java:98]: Done from earlier PR

Comment (brandonywl) [reply src/main/java/seedu/duke/ui/Formatter.java:98]: Will resolve convo when confirmed after merging.
