### PR TITLE
Changes from Code Review

### LINKED ISSUE #54: Code Review
~~Remove SystemException from Command classes. (AddNoteCommand, DeleteEventCommand) (@Nazryl, @brandonywl)~~
~~Remove NULL_INT from Command (@prachi2023)~~
~~Create COMMAND_SUCCESSFUL_MESSAGE and COMMAND_UNSUCCESSFUL_MESSAGE for respective Command classes (@Nazryl, @brandonywl, @prachi2023, @R-Ramana)~~
~~Toggle function for pinning of notes (@prachi2023)~~
~~Update ViewNoteCommand to print note title and tags (@prachi2023)~~
~~Update prepareListNote to follow the format of other prepare functions (@R-Ramana)~~
~~Change private static final COMMAND_USAGE to public and remove getCommandUsage (@R-Ramana)~~
~~Pass storageManager into Command class (@Chongjx)~~

### PR DESCRIPTION
**Pull request by brandonywl**
Added COMMAND_SUCCESS and COMMAND_UNSUCCESSFUL MESSAGES for all command I implemented. Removed SystemException from DeleteEventCommand.

Closes #54

### CODE REVIEW

**Review by R-Ramana — APPROVED** [review]

File: src/main/java/seedu/duke/command/AddEventCommand.java [hunk 1]
```diff
@@ -40,6 +40,7 @@ public static String getCommandUsage() {
     }
 
     private static final String COMMAND_SUCCESSFUL_MESSAGE = "Added the following!";
+    // Command not expected to fail at this stage
```
Comment (Chongjx) [inline src/main/java/seedu/duke/command/AddEventCommand.java:43]: Shld this comment be above? or somewhere in execute? Looks a little out of place

**Review by Chongjx — APPROVED** [review]
Looks good, just 1 question on the comment

File: src/main/java/seedu/duke/command/DeleteEventCommand.java [hunk 2]
```diff
@@ -28,6 +27,8 @@ public static String getCommandUsage() {
     }
 
     private static final String COMMAND_SUCCESSFUL_MESSAGE = "Event deleted:" + InterfaceManager.LS;
+    private static final String COMMAND_UNSUCCESSFUL_MESSAGE = "Event failed to delete: " + InterfaceManager.LS;
+    private static final String INDEX_OUT_OF_RANGE = "Index is out of range.";
```
Comment (R-Ramana) [inline src/main/java/seedu/duke/command/DeleteEventCommand.java:31]: To standardize with your other PR
```suggestion
    private static final String INDEX_OUT_OF_RANGE_MESSAGE = "Index is out of range.";
```

**Review by R-Ramana — CHANGES_REQUESTED** [review]
Just one small catch

File: src/main/java/seedu/duke/command/AddEventCommand.java (hunk 1 above)
Comment (brandonywl) [reply src/main/java/seedu/duke/command/AddEventCommand.java:43]: I placed it here because following the rest I thought we would expect a COMMAND_UNSUCCESSFUL_MESSAGE. Can remove comment as well.

Comment (brandonywl) [reply src/main/java/seedu/duke/command/AddEventCommand.java]: I've re-worded the comment to be clearer as to what it means so it doesn't look as weird

**Review by Chongjx — APPROVED** [review]

**Review by R-Ramana — APPROVED** [review]
